### ISSUE TITLE
明文密码会显示在隐藏的密码前  贴的你的code

### ISSUE THREAD

**Issue by les10281502** [wayne214/react-native-password-pay#1]
![image](https://user-images.githubusercontent.com/46141299/53396556-b2b1d580-39df-11e9-843e-abdf23290237.png)

**Comment by les10281502** [comment]
看到请回答

**Comment by lcyisgod** [comment]
老哥解决这个问题了嘛？

**Comment by wayne214** [comment]
> 看到请回答
sorry,I am busy recently. I have fix it

**Comment by wayne214** [comment]
> 老哥解决这个问题了嘛？
it has been solved
